### ISSUE TITLE
Unknown error occurred when adding entry

### ISSUE THREAD

**Issue by oudoulj** [droso-hass/idfm#28]
The integration was reporting `Unknown` for a couple of sensors I had running just fine so I re-downloaded the integration (v2.3.0), generated a new token and tried to add sensors again.
But everytime I submit, I get `Unknown error occurred` :confused: 
(no matter what I choose, bus, train, different stations, etc...)

What am doing wrong or has something changed?...

![image](https://github.com/droso-hass/idfm/assets/6011092/4162c8c9-882e-4426-93f8-c588b52ed41a)

**Comment by hidrissi-hass** [comment]
I have the same problème.
The Sonsor that contains the next stop schedule does not update.

**Comment by oudoulj** [comment]
It's been over a year and I thought I would give it another spin with the newest 2.3.1 version but still no dice even after uninstalling/reinstalling the integration 😿 
Has anyone found out what's wrong?

![Image](https://github.com/user-attachments/assets/35d5dc2d-af98-4bfa-bf4f-b6a693c79913)

**Comment by drosoCode** [comment]
Hi !
To debug this issue, I would need additionnal information, could you:
- provide the version of home assistant used
- provide any of the previous steps done (which mode, line, stop ...)
- enable debug logs on the integration page, retry the process of adding a new device, and send me the logs

Ps: I don't have a lot of time to dedicate to this project, so sorry in advance if I take a long time to answer

**Comment by MaxLeb** [comment]
Here is a more detailed report.
I may have time to take a look at it.

Adding: Train =>  E => `Chelles - Gournay -Chelles`

<img width="410" height="339" alt="Image" src="https://github.com/user-attachments/assets/8681a18a-aa23-4f56-9830-f1eede56947e" />

HA Version: 

<img width="614" height="339" alt="Image" src="https://github.com/user-attachments/assets/a41c0b29-8e9d-4fad-a7f9-5774eccac3a0" />

 Logs:

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py:481
First occurred: 11:28:24 (1 occurrence)
Last logged: 11:28:24

Error handling request from 2a01:cb08:3:8200:e426:e011:1839:56b0
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 87, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 41, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 83, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 234, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 121, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 336, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 383, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 483, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/idfm/config_flow.py", line 133, in async_step_stop
    return await self.async_step_direction()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/idfm/config_flow.py", line 168, in async_step_direction
    directions = await self._client.get_directions(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/idfm_api/__init__.py", line 225, in get_directions
    for i in await self.get_traffic(stop_id, line_id=line_id):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/idfm_api/__init__.py", line 170, in get_traffic
    response = await self.__request(request + line)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/idfm_api/__init__.py", line 52, in __request
    err = (await response.json())["Siri"]["ServiceDelivery"][
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 773, in json
    return loads(stripped.decode(encoding))
  File "/usr/local/lib/python3.13/json/__init__.py", line 352, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

EDIT: totally linked to https://github.com/droso-hass/idfm/issues/44  and https://github.com/droso-hass/idfm-api/pull/7

**Comment by Givardon186000** [comment]
J'ai eu ce problème aussi et ca vient des limites d'utilisation. C'est bizarre mais à la première configuration on dépasse largement les 1000 requêtes des temps en direct il faut donc appuyer sur plus dans la liste ma consommation afin d'avoir 1 000 000 de requêtes possibles

**Comment by q-pall** [comment]
J'ai le même problème. "Unknown error occurred" lors de la tentative d'ajout d'une nouvelle ligne (au moment de la sélection de l'arrêt)
- multiples essaies faits avec de nombreuses lignes/arrêts.
- Token vérifié
- très loins des quotas idfm (augmentés sur prmi)
- HA redémarré pour mettre à jour les arrêts/lignes.
- la ligne déjà ajoutée fonctionne parfaitement et se met bien à jour

Je ne sais plus vraiement dans quelle direction chercher...
Merci par avance pour l'aide!!


I am facing the exact same issue: "Unknown error occurred" when trying to add a new line (right after selecting the stop).
Here is what I have checked/tested so far:
- Tried multiple times with different lines and stops.
- Verified my API token.
- Quotas are not an issue (far below limits, limits were also increased on the PRIM portal).
- Restarted HA to refresh lines/stops data.
- existing line working perfectly and updating without any problem

I'm out of ideas on where to look next...
Thanks in advance for your help!

_____________________________________________________________________________________________________________
Logs:
Cette erreur provient d'une intégration personnalisée.

Logger: idfm_api
Source: custom_components/idfm/config_flow.py:168
Intégration: Ile de france Mobilite (Documentation, Problèmes)
Première occurrence: 18:01:09 (1 occurrence)
Dernier enregistrement: 18:01:09

Error while fetching information from https://prim.iledefrance-mobilites.fr/marketplace/stop-monitoring?MonitoringRef=STIF:StopArea:SP:71808:&LineRef=STIF:Line::C01373: - b'{"message":"Unauthorized"}'
