### ISSUE TITLE
Issue upon creation of bus line with no bus (at time of creation)

### ISSUE THREAD

**Issue by jugla** [droso-hass/idfm#3]
Hello,
I wanted to test the new V1.1.1 (seems to be great).

On Bus Line 192, I think I have nothing on timetable at right moment .
So for direction, at creation "any" choice is proposed.
I got the following error : 
 '2022-04-15 19:18:26 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform idfm
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 447, in _async_add_entity
    suggested_object_id = entity.name  # type: ignore[unreachable]
  File "/home/homeassistant/.homeassistant/custom_components/idfm/sensor.py", line 50, in name
    "idfm_"
TypeError: can only concatenate str (not "NoneType") to str
`

**Comment by drosoCode** [comment]
This shoud be fixed in v1.1.2

**Comment by jugla** [comment]
Great !
Thank you for your quick answer !

**Comment by jugla** [comment]
Thanks it works!
I have notived that in sensor name, there is no more the name of the line (in binary, it is still there). E.g. REB_B
