### ISSUE TITLE
Error adding entities for domain sensor with platform idfm

### ISSUE THREAD

**Issue by jugla** [droso-hass/idfm#8]
In logs you have
`
2022-04-22 13:12:53 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform idfm
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 799, in add_to_platform_finish
    self.async_write_ha_state()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/home/homeassistant/.homeassistant/custom_components/idfm/sensor.py", line 67, in state
    data = sorted(self.coordinator.data[DATA_TRAFFIC], key=lambda x: x.schedule)
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.datetime'

`

**Comment by drosoCode** [comment]
This should be fixed by v1.1.4

**Comment by jugla** [comment]
Works well !!
Thanks !
